name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *" # ежедневно в 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    name: Build snake SVG
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Martovetskiy
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Publish to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
